[
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70001" },
    "name": "Spicy Tom Yum Goong Soup",
    "description": "Hot and sour soup with shrimp, lemongrass, galangal, and mushrooms.",
    "price": 13.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/tomyum.jpg",
    "ingredients": ["shrimp", "lemongrass", "chili", "mushroom"],
    "dietaryTags": ["spicy", "seafood"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70002" },
    "name": "Chicken Satay Skewers",
    "description": "Marinated grilled chicken skewers, served with peanut sauce and cucumber relish.",
    "price": 9.50,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/satay.jpg",
    "ingredients": ["chicken", "peanut butter", "turmeric"],
    "dietaryTags": ["contains-nuts"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70003" },
    "name": "Chicken Pad See Ew",
    "description": "Wide rice noodles stir-fried with chicken, egg, and Chinese broccoli in dark soy sauce.",
    "price": 15.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/padseeew.jpg",
    "ingredients": ["noodles", "chicken", "egg", "soy sauce"],
    "dietaryTags": ["nut-free"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70004" },
    "name": "Green Curry with Tofu",
    "description": "Tofu, bamboo shoots, and basil simmered in a creamy green coconut milk curry.",
    "price": 16.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/green_curry.jpg",
    "ingredients": ["tofu", "coconut milk", "bamboo", "basil"],
    "dietaryTags": ["vegan", "gluten-free", "spicy"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70005" },
    "name": "Pineapple Fried Rice",
    "description": "Fried rice with shrimp, chicken, cashews, raisins, and curry powder, served in a pineapple.",
    "price": 18.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/pineapple_rice.jpg",
    "ingredients": ["rice", "shrimp", "chicken", "cashews"],
    "dietaryTags": ["contains-nuts", "seafood"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70006" },
    "name": "Spicy Basil Stir-fry (Pad Krapow)",
    "description": "Wok-tossed ground pork with chili, garlic, green beans, and Thai basil.",
    "price": 15.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/pad_krapow.jpg",
    "ingredients": ["pork", "basil", "chili", "garlic"],
    "dietaryTags": ["very-spicy"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70007" },
    "name": "Coconut Sticky Rice",
    "description": "Sweet glutinous rice steamed with coconut milk and sugar.",
    "price": 4.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/stickyrice.jpg",
    "ingredients": ["rice", "coconut milk"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70008" },
    "name": "Jasmine Rice",
    "description": "A serving of fragrant, fluffy Thai Jasmine white rice.",
    "price": 3.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/jasminerice.jpg",
    "ingredients": ["rice"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70009" },
    "name": "Thai Iced Tea",
    "description": "Strongly brewed black tea sweetened with sugar and condensed milk.",
    "price": 5.00,
    "category": "Drinks",
    "isAvailable": true,
    "imageURL": "https://example.com/thai_iced_tea.jpg",
    "ingredients": ["black tea", "condensed milk"],
    "dietaryTags": ["dairy"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000a" },
    "name": "Mango Sticky Rice (Dessert)",
    "description": "Sweet sticky rice topped with coconut milk and fresh sliced mango.",
    "price": 9.50,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/mangorice.jpg",
    "ingredients": ["mango", "rice", "coconut milk"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "Thailand"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000b" },
    "name": "Salted Edamame",
    "description": "Steamed and lightly salted young soybeans in the pod.",
    "price": 6.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/edamame.jpg",
    "ingredients": ["soybeans", "salt"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000c" },
    "name": "Pork Gyoza",
    "description": "Pan-fried Japanese dumplings filled with seasoned ground pork and cabbage.",
    "price": 9.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/gyoza.jpg",
    "ingredients": ["pork", "cabbage", "wheat"],
    "dietaryTags": ["dairy-free"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000d" },
    "name": "Classic Tonkotsu Ramen",
    "description": "Rich pork broth with thin noodles, chashu pork, soft-boiled egg, and nori.",
    "price": 19.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/tonkotsu.jpg",
    "ingredients": ["pork broth", "noodles", "pork", "egg"],
    "dietaryTags": ["pork"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000e" },
    "name": "Tempura Shrimp and Vegetables",
    "description": "Assortment of shrimp and seasonal vegetables lightly battered and deep-fried.",
    "price": 21.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/tempura.jpg",
    "ingredients": ["shrimp", "flour", "vegetables"],
    "dietaryTags": ["seafood"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7000f" },
    "name": "Spicy Tuna Roll (8pcs)",
    "description": "Rolled sushi with spicy minced tuna, cucumber, and a sprinkle of sesame seeds.",
    "price": 14.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/spicy_tuna.jpg",
    "ingredients": ["tuna", "rice", "seaweed", "cucumber"],
    "dietaryTags": ["seafood", "raw-fish", "spicy"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70010" },
    "name": "Chicken Teriyaki Bowl",
    "description": "Grilled chicken glazed with sweet teriyaki sauce, served over rice with a side salad.",
    "price": 17.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/teriyaki.jpg",
    "ingredients": ["chicken", "soy sauce", "sugar", "rice"],
    "dietaryTags": ["dairy-free"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70011" },
    "name": "Miso Soup",
    "description": "Traditional soup made from miso paste, dashi, tofu, and seaweed.",
    "price": 4.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/miso.jpg",
    "ingredients": ["miso", "tofu", "seaweed"],
    "dietaryTags": ["vegetarian"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70012" },
    "name": "Sunomono Salad",
    "description": "Cool cucumber and seaweed marinated in a light, sweet vinegar dressing.",
    "price": 7.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/sunomono.jpg",
    "ingredients": ["cucumber", "seaweed", "vinegar"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70013" },
    "name": "Mochi Ice Cream",
    "description": "Sweet pounded rice cake with a matcha or strawberry ice cream filling.",
    "price": 6.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/mochi.jpg",
    "ingredients": ["rice flour", "ice cream", "sugar"],
    "dietaryTags": ["gluten-free"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70014" },
    "name": "Matcha Cheesecake",
    "description": "A creamy cheesecake flavored with Japanese green tea powder.",
    "price": 9.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/matcha_cheesecake.jpg",
    "ingredients": ["cream cheese", "matcha", "sugar", "crust"],
    "dietaryTags": ["dairy"],
    "country": "Japan"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70015" },
    "name": "Classic Buffalo Wings (6pc)",
    "description": "Deep-fried chicken wings tossed in Frank's Red Hot sauce. Served with blue cheese dip.",
    "price": 14.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/buffalowings.jpg",
    "ingredients": ["chicken", "hot sauce", "blue cheese"],
    "dietaryTags": ["spicy", "dairy"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70016" },
    "name": "Nachos Supreme",
    "description": "Crispy tortilla chips piled high with chili, cheese sauce, jalapeños, and sour cream.",
    "price": 17.50,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/nachos.jpg",
    "ingredients": ["tortilla", "cheese", "beef/chili", "jalapeño"],
    "dietaryTags": ["spicy"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70017" },
    "name": "Gourmet Cheeseburger",
    "description": "8oz beef patty, aged cheddar, lettuce, tomato, and signature sauce on a toasted bun.",
    "price": 18.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/cheeseburger.jpg",
    "ingredients": ["beef", "cheddar", "bun", "lettuce"],
    "dietaryTags": ["dairy"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70018" },
    "name": "Smoked BBQ Pulled Pork Sandwich",
    "description": "Slow-smoked pulled pork tossed in a tangy Carolina BBQ sauce on a brioche bun.",
    "price": 16.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/pulledpork.jpg",
    "ingredients": ["pork", "bbq sauce", "bun", "coleslaw"],
    "dietaryTags": ["pork", "nut-free"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70019" },
    "name": "Classic Mac and Cheese",
    "description": "Elbow macaroni baked in a creamy blend of three sharp cheeses.",
    "price": 14.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/macncheese.jpg",
    "ingredients": ["macaroni", "cheddar", "milk", "butter"],
    "dietaryTags": ["vegetarian", "dairy", "comfort-food"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001a" },
    "name": "Caesar Salad",
    "description": "Romaine lettuce, crunchy croutons, parmesan cheese, and a creamy Caesar dressing.",
    "price": 12.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/caesar.jpg",
    "ingredients": ["romaine", "croutons", "parmesan", "dressing"],
    "dietaryTags": ["dairy", "gluten-free-option"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001b" },
    "name": "French Fries (Basket)",
    "description": "A large basket of classic thin-cut, salted potato French fries.",
    "price": 6.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/fries.jpg",
    "ingredients": ["potatoes", "salt", "oil"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001c" },
    "name": "Onion Rings",
    "description": "Thick-cut onion rings, battered and deep-fried to a golden crisp.",
    "price": 7.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/onionrings.jpg",
    "ingredients": ["onion", "batter", "oil"],
    "dietaryTags": ["vegetarian"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001d" },
    "name": "Apple Pie",
    "description": "Warm, flaky crust filled with spiced baked apples, served à la mode.",
    "price": 9.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/applepie.jpg",
    "ingredients": ["apples", "cinnamon", "pie crust", "ice cream"],
    "dietaryTags": ["dairy-option"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001e" },
    "name": "New York Cheesecake",
    "description": "Rich, dense, and creamy cheesecake with a graham cracker crust.",
    "price": 10.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/cheesecake.jpg",
    "ingredients": ["cream cheese", "graham cracker", "sugar", "egg"],
    "dietaryTags": ["dairy"],
    "country": "USA"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7001f" },
    "name": "Pork Potstickers (6pc)",
    "description": "Pan-fried dumplings filled with seasoned pork and vegetables.",
    "price": 8.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/potstickers.jpg",
    "ingredients": ["pork", "cabbage", "ginger", "flour"],
    "dietaryTags": ["pork"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70020" },
    "name": "Egg Drop Soup",
    "description": "Thick, savory soup with ribbons of whisked eggs and green onions.",
    "price": 5.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/eggdropsoup.jpg",
    "ingredients": ["chicken broth", "egg", "scallion"],
    "dietaryTags": ["gluten-free"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70021" },
    "name": "Kung Pao Chicken",
    "description": "Diced chicken, peanuts, vegetables, and chili peppers stir-fried with a sweet and savory sauce.",
    "price": 17.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/kungpao.jpg",
    "ingredients": ["chicken", "peanut", "chili", "soy sauce"],
    "dietaryTags": ["contains-nuts", "spicy"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70022" },
    "name": "Beef and Broccoli",
    "description": "Slices of marinated beef and fresh broccoli florets tossed in a ginger-soy sauce.",
    "price": 18.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/beefbroccoli.jpg",
    "ingredients": ["beef", "broccoli", "soy sauce", "ginger"],
    "dietaryTags": ["gluten-free-option"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70023" },
    "name": "Sweet and Sour Pork",
    "description": "Deep-fried pork pieces coated in a bright red, sweet and sour sauce with pineapple and bell peppers.",
    "price": 16.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/sweet_sour_pork.jpg",
    "ingredients": ["pork", "pineapple", "bell pepper", "sugar"],
    "dietaryTags": ["pork"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70024" },
    "name": "Vegetable Lo Mein",
    "description": "Soft wheat noodles stir-fried with seasonal vegetables and a savory brown sauce.",
    "price": 14.50,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/lomein.jpg",
    "ingredients": ["noodles", "cabbage", "carrot", "onion"],
    "dietaryTags": ["vegetarian"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70025" },
    "name": "White Rice (Side)",
    "description": "A serving of plain, steamed long-grain white rice.",
    "price": 3.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/whiterice.jpg",
    "ingredients": ["rice", "water"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70026" },
    "name": "Hot and Sour Soup",
    "description": "Spicy and tangy soup with mushrooms, bamboo shoots, tofu, and black vinegar.",
    "price": 6.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/hotsoursoup.jpg",
    "ingredients": ["tofu", "bamboo", "vinegar", "chili"],
    "dietaryTags": ["vegetarian", "spicy"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70027" },
    "name": "Sesame Balls (Jian Dui)",
    "description": "Sweet fried dough covered in sesame seeds, filled with sweet red bean paste.",
    "price": 7.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/sesameballs.jpg",
    "ingredients": ["rice flour", "sesame", "red bean"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70028" },
    "name": "Fortune Cookies",
    "description": "Crispy vanilla cookies containing a piece of paper with a wise saying.",
    "price": 1.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/fortune_cookie.jpg",
    "ingredients": ["flour", "sugar", "vanilla"],
    "dietaryTags": ["vegetarian"],
    "country": "China"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70029" },
    "name": "Vegetable Samosas (2pc)",
    "description": "Crispy fried pastries filled with spiced potatoes and peas. Served with mint chutney.",
    "price": 7.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/samosa.jpg",
    "ingredients": ["potato", "peas", "flour", "spices"],
    "dietaryTags": ["vegan"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002a" },
    "name": "Paneer Pakora",
    "description": "Cubes of Indian cottage cheese dipped in a spiced chickpea batter and deep-fried.",
    "price": 9.00,
    "category": "Appetizers",
    "isAvailable": true,
    "imageURL": "https://example.com/paneer_pakora.jpg",
    "ingredients": ["paneer", "chickpea flour", "spices"],
    "dietaryTags": ["vegetarian", "gluten-free", "dairy"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002b" },
    "name": "Chicken Tikka Masala",
    "description": "Marinated chicken pieces in a creamy, mildly spiced tomato sauce.",
    "price": 18.99,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/tikka.jpg",
    "ingredients": ["chicken", "yogurt", "tomato", "cream"],
    "dietaryTags": ["dairy"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002c" },
    "name": "Lamb Rogan Josh",
    "description": "Aromatic Kashmiri curry dish made with tender lamb pieces and a rich gravy.",
    "price": 23.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/rogan_josh.jpg",
    "ingredients": ["lamb", "ginger", "fennel", "yogurt"],
    "dietaryTags": ["spicy"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002d" },
    "name": "Vegetable Biryani",
    "description": "Fragrant basmati rice dish cooked with mixed vegetables, herbs, and spices.",
    "price": 16.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/biryani.jpg",
    "ingredients": ["rice", "carrot", "peas", "cauliflower"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002e" },
    "name": "Aloo Gobi",
    "description": "Dry curry made with potatoes (aloo), cauliflower (gobi), and Indian spices.",
    "price": 15.00,
    "category": "Entrees",
    "isAvailable": true,
    "imageURL": "https://example.com/aloogobi.jpg",
    "ingredients": ["potato", "cauliflower", "turmeric", "cumin"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f7002f" },
    "name": "Garlic Naan",
    "description": "Leavened flatbread brushed with garlic butter and cilantro.",
    "price": 4.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/garlic_naan.jpg",
    "ingredients": ["flour", "yogurt", "garlic", "butter"],
    "dietaryTags": ["vegetarian", "dairy"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70030" },
    "name": "Papadum Basket",
    "description": "Thin, crispy lentil crackers served with a variety of dips.",
    "price": 5.00,
    "category": "Sides",
    "isAvailable": true,
    "imageURL": "https://example.com/papadum.jpg",
    "ingredients": ["lentil flour", "spices"],
    "dietaryTags": ["vegan", "gluten-free"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70031" },
    "name": "Gulab Jamun",
    "description": "Deep-fried milk solids balls soaked in a rose-flavored sugar syrup.",
    "price": 7.50,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/gulab_jamun.jpg",
    "ingredients": ["milk solids", "sugar", "rosewater"],
    "dietaryTags": ["vegetarian", "dairy"],
    "country": "India"
  },
  {
    "_id": { "$oid": "66f7f631a0b3c4d5e6f70032" },
    "name": "Kulfi (Pistachio)",
    "description": "Traditional Indian frozen dessert, richer and denser than ice cream, flavored with pistachio.",
    "price": 8.00,
    "category": "Desserts",
    "isAvailable": true,
    "imageURL": "https://example.com/kulfi.jpg",
    "ingredients": ["milk", "sugar", "pistachio"],
    "dietaryTags": ["contains-nuts", "dairy", "gluten-free"],
    "country": "India"
  }
]